In [1]:
import numpy as np
import pandas as pd

### Question 1 (NumPy) – Titanic Dataset Survival Analysis

In [ ]:
# loading data
titanic_df = pd.read_csv('C:/Users/SUNIL/Desktop/G34-Python/Exams/pandas n numpy/Titanic-Dataset.csv')

In [3]:
titanic_df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [64]:
#converting ['Age','Fare' and 'Survived'] to array format
arr = np.array(titanic_df[['Age','Fare','Survived']])
arr

array([[22.    ,  7.25  ,  0.    ],
       [38.    , 71.2833,  1.    ],
       [26.    ,  7.925 ,  1.    ],
       ...,
       [    nan, 23.45  ,  0.    ],
       [26.    , 30.    ,  1.    ],
       [32.    ,  7.75  ,  0.    ]])

In [ ]:
# filtering missing values
arr = arr[~np.isnan(arr).any(axis=1)]
arr

array([[22.    ,  7.25  ,  0.    ],
       [38.    , 71.2833,  1.    ],
       [26.    ,  7.925 ,  1.    ],
       ...,
       [19.    , 30.    ,  1.    ],
       [26.    , 30.    ,  1.    ],
       [32.    ,  7.75  ,  0.    ]])

In [ ]:
#creating backup
arr_cleaned = arr.copy()
arr_cleaned

array([[22.    ,  7.25  ,  0.    ],
       [38.    , 71.2833,  1.    ],
       [26.    ,  7.925 ,  1.    ],
       ...,
       [19.    , 30.    ,  1.    ],
       [26.    , 30.    ,  1.    ],
       [32.    ,  7.75  ,  0.    ]])

In [ ]:
# finding mean and std for age and fare
age_mean = arr[:, 0].mean()
age_std = arr[:, 0].std()

fare_mean = arr[:, 1].mean()
fare_std = arr[:, 1].std()

In [ ]:
# normalizing using z-score = (x- x_mean)/x_standard_deviation
arr[:, 0] = (arr[:, 0] - age_mean)/age_std
arr[:, 1] = (arr[:, 1] - fare_mean)/fare_std

In [ ]:
# finding survived and not survived 
not_survived = arr_cleaned[arr_cleaned[:, -1] == 0]
survived = arr_cleaned[arr_cleaned[:, -1] == 1]

In [ ]:
# filtering array based on survival
survived_arr = arr_cleaned[arr_cleaned[:, 2] == 1]
not_survived_arr = arr_cleaned[arr_cleaned[:, 2] == 0]

In [ ]:
# finding mean age and fare for survived and not survived
not_survived_mean_age = not_survived_arr[:, 0].mean()
not_survived_mean_fare = not_survived_arr[:, 1].mean()

survived_mean_age = survived_arr[:, 0].mean()
survived_mean_fare = survived_arr[:, 1].mean()

In [ ]:
# mean age and fare value for survived and not survived passengers
print("Not Survived - Mean Age:", not_survived_mean_age, "Mean Fare:", not_survived_mean_fare)
print("Survived     - Mean Age:", survived_mean_age, "Mean Fare:", survived_mean_fare)

Not Survived - Mean Age: 30.62617924528302 Mean Fare: 22.96545636792453
Survived     - Mean Age: 28.343689655172415 Mean Fare: 51.843205172413796


In [ ]:
# classification where fare is low or high than mean values
fare = arr_cleaned[:, 1]
mean_fare = fare.mean()

fare_classification = np.where(fare< mean_fare, 'Low', 'High')

print(fare_classification)


['Low' 'High' 'Low' 'High' 'Low' 'High' 'Low' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Low'
 'High' 'Low' 'Low' 'High' 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'High'
 'Low' 'Low' 'High' 'Low' 'High' 'Low' 'High' 'Low' 'Low' 'Low' 'High'
 'Low' 'High' 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'High'
 'Low' 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Low'
 'High' 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Low' 'High' 'Low' 'Low'
 'Low' 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Low' 'Low' 'High' 'Low' 'High' 'Low' 'Low' 'High' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'High' 'Low'
 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Low'
 'High' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'High'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Lo

### Question 2 (Pandas) – Iris Dataset Summary Report 

In [ ]:
# loading dataset
iris_df = pd.read_excel('C:/Users/SUNIL/Desktop/G34-Python/Exams/pandas n numpy/iris.xlsx')
iris_df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
# creating column petal ratio
iris_df['petal_ratio'] = iris_df['petal.length']/iris_df['petal.width']
iris_df

sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa   
1             4.9          3.0           1.4          0.2     Setosa   
2             4.7          3.2           1.3          0.2     Setosa   
3             4.6          3.1           1.5          0.2     Setosa   
4             5.0          3.6           1.4          0.2     Setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  Virginica   
146           6.3          2.5           5.0          1.9  Virginica   
147           6.5          3.0           5.2          2.0  Virginica   
148           6.2          3.4           5.4          2.3  Virginica   
149           5.9          3.0           5.1          1.8  Virginica   

     petal_ratio  
0       7.000000  
1       7.000000  
2       6.500000  
3       7.500000  
4       7.000000  
..           ...  
145     2.260870  
146     2.631579  
147     2.600000  
148     2.347826  
149     2.833333  

[150 rows x 6 columns]

In [ ]:
# average mean per species
iris_df.groupby('variety')['petal_ratio'].mean()

variety
Setosa        6.908000
Versicolor    3.242837
Virginica     2.780662
Name: petal_ratio, dtype: float64

In [101]:

species_high_std = iris_df.groupby('variety')['sepal.length'].std().sort_values(ascending=False).index[0]
print(f' {species_high_std} has the highest standard deviation in sepal length')

 Virginica has the highest standard deviation in sepal length


In [ ]:
# filtering the dataset where sepal_width is above the overall mean
iris_df[iris_df['sepal.width'] > iris_df['sepal.width'].mean()]

sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa   
2             4.7          3.2           1.3          0.2     Setosa   
3             4.6          3.1           1.5          0.2     Setosa   
4             5.0          3.6           1.4          0.2     Setosa   
5             5.4          3.9           1.7          0.4     Setosa   
..            ...          ...           ...          ...        ...   
140           6.7          3.1           5.6          2.4  Virginica   
141           6.9          3.1           5.1          2.3  Virginica   
143           6.8          3.2           5.9          2.3  Virginica   
144           6.7          3.3           5.7          2.5  Virginica   
148           6.2          3.4           5.4          2.3  Virginica   

     petal_ratio  
0       7.000000  
2       6.500000  
3       7.500000  
4       7.000000  
5       4.250000  
..           ...  
140     2.333333  
141     2.217391  
143     2.565217  
144     2.280000  
148     2.347826  

[67 rows x 6 columns]

In [ ]:
# splitting dataset into two parts one with petal_ratio >= 2 and other petal_ratio < 2
df1 = iris_df[iris_df['petal.width'] < 2]
df2 = iris_df[iris_df['petal.width'] >= 2]

In [ ]:
#concating them vertically
pd.concat([df1, df2], axis=0)

sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa   
1             4.9          3.0           1.4          0.2     Setosa   
2             4.7          3.2           1.3          0.2     Setosa   
3             4.6          3.1           1.5          0.2     Setosa   
4             5.0          3.6           1.4          0.2     Setosa   
..            ...          ...           ...          ...        ...   
143           6.8          3.2           5.9          2.3  Virginica   
144           6.7          3.3           5.7          2.5  Virginica   
145           6.7          3.0           5.2          2.3  Virginica   
147           6.5          3.0           5.2          2.0  Virginica   
148           6.2          3.4           5.4          2.3  Virginica   

     petal_ratio  
0       7.000000  
1       7.000000  
2       6.500000  
3       7.500000  
4       7.000000  
..           ...  
143     2.565217  
144     2.280000  
145     2.260870  
147     2.600000  
148     2.347826  

[150 rows x 6 columns]